### ISSUE TITLE
Unknown package mis-placed in devDependencies instead of dependencies in package.json

### ISSUE THREAD

**Issue by AndrewFarley** [Couchers-org/web-frontend#25]
There is/was a bug in our package.json, specifically some package that is in devDependencies should be in dependencies.  This causes our code to not work properly when only the prod dependencies are installed which is ideally how we should run this in production.  However, the old Dockerfile installed the prod dependencies "over" the dev ones, such that both were always installed.  When we pivoted over to Kubernetes and cleaning everything up, we ran into this insane issue which took us a week to get to the bottom of specifically because there wasn't good/any logging or debug information telling us why it was crashing.  The NodeJS process would exit with exit code 137, which is an "OOM", but this had nothing to do with memory.  In checking metrics and in testing giving it tons of RAM it was still exiting with this code, and was giving no logs as to why it was failing.

The temporary fix is to use all the dev node_modules in production, making our docker image larger and our ability to scale/deploy a bit slower.  The "temporary" fix is shown below, which when the package.json is fixed can and should be reverted.

See: https://github.com/Couchers-org/web-frontend/pull/24/files

**Comment by guillermodlpa** [comment]
I wonder what package it is/are. I've looked at the list of `devDependencies` and, at a glance, all of them seem properly placed there because they are for local development, building, or testing.

If the Dockerfile is building the production bundles, then it might make sense to pull all dependencies. I think this differentiation makes more sense for packages that are imported via npm. But for the production Docker images, they should only have the bundled code anyway, not the source of our repo or the source of the dependencies, right? I'm not an expert here so I might be wrong.

**Comment by AndrewFarley** [comment]
@guillermodlpa The dev deps are needed for build time (which is what we do) but shouldn't ever be needed for runtime.  This bug is highlighting that fact.

**Comment by guillermodlpa** [comment]
Yeah, that makes sense. What I don't understand is why it's an issue 🤔 

When we build with Webpack, Webpack takes care of only including the necessary code in the production bundle automatically. It doesn't really matter if a dependency is listed in `dependencies` or `devDependencies`, because it will only be part of the production bundle if any application code uses it.

[Since the Dockerfile is building the bundles](https://github.com/Couchers-org/web-frontend/blob/master/Dockerfile#L44), then we need all dependencies there, including dev ones, so Webpack compilation can run as expected.

The separation between `devDependencies` and `dependencies` I think it's more meant for the use case of importing npm packages. For example, when we import the dependency `react` in our project, NPM only loads `dependencies` because it knows we're using the package, not really needing to develop on it.

**Comment by lucaslcode** [comment]
I'm going to throw a spanner in the works and add to the mystery by pointing out that the nextjs server doesn't actually use node_modules, at all.

If you take a look at [their example Dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile), only things from the build folder (`.next`) are included in the runner, which includes dependencies. I also notice their run command is `node server.js` not `yarn next start` - maybe that's what we're missing?

**Comment by thdk** [comment]
Hi folks :) 

I got this issue in my inbox and just found this setting today which I believe could help you get smaller docker images for nextjs apps:

https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files-experimental

**Comment by AndrewFarley** [comment]
Nice work team.  If anyone's bored free to submit a MR fixing this I'd be happy to review it, if it works it should build and deploy and function on the dynamic development environment via Github Actions.  I imagine this would indeed make the final docker image much much smaller.
